# orchestrator deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-enforcer
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-enforcer
  template:
    metadata:
      labels:
        app: policy-enforcer
    spec:
      containers:
      - name: policy-enforcer
        image: {{ .Values.dockerArtifactAccount }}/policy-enforcer:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        env:
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
        - name: LANG
          value: C.UTF-8
        - name: LC_ALL
          value: C.UTF-8
        readinessProbe:
          httpGet:
            path: /api/v1/readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: eflint-states
          mountPath: /app/eflint-states
        - name: eflint-models
          mountPath: /app/eflint-models
          subPath: eflint-models
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"

      - name: sidecar
        image: {{ .Values.dockerArtifactAccount }}/sidecar:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
      volumes:
      - name: eflint-states
        emptyDir: {}
      - name: eflint-models
        persistentVolumeClaim:
          claimName: etcd-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: policy-enforcer
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: policy-enforcer
  ports:
    - name: http-policy-enforcer-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
