# export DYNAMOS_ROOT="/home/ubuntu/scattered-directive-energy-monitoring"
export DYNAMOS_ROOT="/mnt/c/Users/alkou/Documents/GitHub/scattered-directive-energy-monitoring"
export DOCKERHUB_ACCOUNT="dynamos1"
export CONFIG_PATH="${DYNAMOS_ROOT}/configuration"
export FABRIC_PATH="${DYNAMOS_ROOT}/fabric"
export CHARTS_LOCAL_PATH="${DYNAMOS_ROOT}/charts"
export CHARTS_FABRIC_PATH="${FABRIC_PATH}/charts"