apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
  namespace: orchestrator
  annotations:
    "linkerd.io/inject" : disabled
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-etcd-pvc
  namespace: orchestrator
spec:
  template:
    metadata:
      annotations:
        "linkerd.io/inject": "disabled"
    spec:
      containers:
      - name: init
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - mkdir -p /etcd/eflint-models
        volumeMounts:
        - name: pvc-volume
          mountPath: /etcd
      restartPolicy: OnFailure
      volumes:
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: etcd-pvc